version: '3'
services:
    spring-test-pg:
        image: postgres:13
        ports:
          - "5432:5432"
        volumes:
          - spring-test-volume:/var/lib/postgresql/data
          - ./db/init:/docker-entrypoint-initdb.d/
        environment:
          - 'POSTGRES_PASSWORD=123'
    spring-app:
        image: spring-test/app
        ports: 
          - 8080:8080
volumes:
  spring-test-volume:
